/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const travel_Logic = require('./code/travel-logic');

class travelSrv extends LCAPApplicationService {
    async init() {

        this.after('READ', 'Travel', async (results, request) => {
            await travel_Logic(results, request);
        });

        return super.init();
    }
}


module.exports = {
    travelSrv
};